name = "noitamap-image-upload-proxy"
main = "src/index.ts"
compatibility_date = "2026-01-20"

[vars]
ALLOWED_ORIGINS = "https://noitamap.com,https://dev.noitamap.com"
UPLOAD_TARGET = "https://catbox.moe/user/api.php"

[env.dev]
name = "noitamap-image-upload-proxy-dev"
[env.dev.vars]
ALLOWED_ORIGINS = "https://dev.noitamap.com,http://localhost:5173,http://localhost:3000"
UPLOAD_TARGET = "https://catbox.moe/user/api.php"
