name = "noitamap-image-upload-proxy"
main = "src/index.ts"
compatibility_date = "2026-01-20"

[vars]
ALLOWED_ORIGINS = "https://noitamap.com,https://dev.noitamap.com,https://vectorize-images.noitamap.com"
UPLOAD_TARGET = "https://catbox.moe/user/api.php"
UPLOAD_TARGET_FALLBACK = "https://qu.ax/upload.php"

[env.dev]
name = "noitamap-image-upload-proxy-dev"
[env.dev.vars]
ALLOWED_ORIGINS = "https://dev.noitamap.com,https://vectorize-images.noitamap.com,http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000"
UPLOAD_TARGET = "https://catbox.moe/user/api.php"
UPLOAD_TARGET_FALLBACK = "https://qu.ax/upload.php"
